"""
Canonical Telemetry Contract for SIH26054 Aero Piston Engine Digital Twin.

Phase 9 Telemetry Ingestion Layer:
- Strictly types all incoming sensor and simulated channels.
- Decouples physical source origin (SourceType) from epistemic data status (QuantityStatus).
- Integrates with Phase 3 DataQualityStatus and QuantityStatus.
- Provides validated lossless interoperability with TelemetryRecord.
- Preserves raw values, raw units, calibration status, and provenance notes.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Dict, Any, Optional, List, Union
import math

from telemetry.schema import TelemetryRecord, FaultCategory
from digital_twin.quality import DataQualityStatus
from digital_twin.state import QuantityStatus


class SourceType(str, Enum):
    """
    Physical data feed origin.
    Strictly decoupled from measurement epistemic status (QuantityStatus).
    """
    SIMULATOR = "SIMULATOR"            # Generated by physics / grey-box engine simulator
    REPLAY = "REPLAY"                  # Replayed from recorded synthetic / benchmark session
    REAL_SENSOR = "REAL_SENSOR"        # Direct physical sensor transducer observation
    DERIVED = "DERIVED"                # Computationally synthesized / algebraic combination
    DEFAULT_ASSUMED = "DEFAULT_ASSUMED"# Unmeasured static parameter / reference baseline


class CalibrationStatus(str, Enum):
    """Sensor transducer calibration state."""
    CALIBRATED = "CALIBRATED"          # Valid calibration curve / scale-offset applied
    UNCALIBRATED = "UNCALIBRATED"      # Raw factory electrical output without calibration
    DEFAULT_ASSUMED = "DEFAULT_ASSUMED"# Default nominal scale/offset assumed


@dataclass
class CalibrationMetadata:
    """Sensor transducer calibration parameters."""
    scale: float = 1.0
    offset: float = 0.0
    calibration_version: str = "1.0"
    calibration_source: str = "factory_nominal"
    calibration_timestamp: Optional[float] = None
    status: CalibrationStatus = CalibrationStatus.UNCALIBRATED
    is_active: bool = False

    def apply(self, raw_val: float) -> float:
        """Apply calibration if marked active, otherwise return raw."""
        if self.is_active:
            return float(raw_val) * self.scale + self.offset
        return float(raw_val)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CanonicalMeasurement:
    """
    A strictly typed, unit-aware observation of a single engine telemetry channel.

    Key Invariants:
    - raw_value is immutable and never overwritten by filtered_value.
    - source_type (origin) is strictly distinct from status (epistemic state).
    - units are explicit and non-negotiable.
    """
    channel_name: str
    value: Optional[float]                         # Numeric value in canonical unit (or None if missing/invalid)
    unit: str                                      # Canonical unit string
    raw_value: Optional[Any] = None                # Original un-sanitized observation
    raw_unit: Optional[str] = None                 # Original unit string prior to conversion
    timestamp: float = 0.0                         # Canonical timestamp driving Digital Twin
    source_timestamp: Optional[float] = None       # Hardware acquisition timestamp at sensor/source
    ingest_timestamp: Optional[float] = None       # Arrival timestamp at telemetry ingestion boundary
    latency: Optional[float] = None                # Ingest latency (ingest_timestamp - source_timestamp)
    sequence_num: Optional[int] = None             # Frame counter sequence number
    source_id: str = "feed_01"                     # Identifier of data stream / DAQ
    source_type: SourceType = SourceType.SIMULATOR # Physical origin category
    quality: DataQualityStatus = DataQualityStatus.VALID # Data validity / boundary status
    status: QuantityStatus = QuantityStatus.MEASURED     # Epistemic quantity status
    sensor_id: Optional[str] = None                # Physical transducer serial / pin identifier
    calibration: Optional[CalibrationMetadata] = None # Transducer calibration parameters
    filtered_value: Optional[float] = None         # Optional filtered/smoothed representation
    notes: str = ""                                # Contextual notes (e.g. "HELD_LAST_VALUE", "INTERPOLATED")

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["source_type"] = self.source_type.value
        d["quality"] = self.quality.value
        d["status"] = self.status.value
        if self.calibration:
            d["calibration"] = self.calibration.to_dict()
        return d


@dataclass
class CanonicalTelemetryPacket:
    """
    A synchronized or atomic frame of canonical telemetry channels.
    Provides lossless and validated interoperability with TelemetryRecord.
    """
    timestamp: float
    source_timestamp: Optional[float] = None
    ingest_timestamp: Optional[float] = None
    latency: Optional[float] = None
    sequence_num: Optional[int] = None
    source_id: str = "feed_01"
    source_type: SourceType = SourceType.SIMULATOR
    schema_version: str = "1.0"
    engine_id: str = "ENGINE_UAV_01"
    mission_id: str = "MISSION_01"
    mission_phase: str = "CRUISE"
    measurements: Dict[str, CanonicalMeasurement] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def get_value(self, channel_name: str, default: Optional[float] = None) -> Optional[float]:
        """Retrieve numeric canonical value of a channel if present and valid."""
        m = self.measurements.get(channel_name)
        if m is not None and m.value is not None:
            return m.value
        return default

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "source_timestamp": self.source_timestamp,
            "ingest_timestamp": self.ingest_timestamp,
            "latency": self.latency,
            "sequence_num": self.sequence_num,
            "source_id": self.source_id,
            "source_type": self.source_type.value,
            "schema_version": self.schema_version,
            "engine_id": self.engine_id,
            "mission_id": self.mission_id,
            "mission_phase": self.mission_phase,
            "measurements": {k: v.to_dict() for k, v in self.measurements.items()},
            "metadata": self.metadata,
        }

    def to_telemetry_record(self) -> TelemetryRecord:
        """
        Lossless and validated bridge to TelemetryRecord.
        Allows the existing Digital Twin synchronizer to consume this packet seamlessly.
        """
        # Extract core mandatory physical channels
        alt = self.get_value("altitude", 2000.0)
        amb_t = self.get_value("ambient_temp", 15.0)
        thr = self.get_value("throttle", 75.0)
        lod = self.get_value("load", 70.0)
        rpm_val = self.get_value("rpm", 5000.0)
        cht_val = self.get_value("cht", 110.0)
        egt_val = self.get_value("egt", 800.0)
        oil_t = self.get_value("oil_temp", 95.0)
        oil_p = self.get_value("oil_pressure", 3.5)
        fuel_f = self.get_value("fuel_flow", 22.0)
        vib = self.get_value("vibration", 0.8)

        # Build TelemetryRecord
        rec = TelemetryRecord(
            timestamp=float(self.timestamp),
            mission_id=str(self.mission_id),
            engine_id=str(self.engine_id),
            mission_phase=str(self.mission_phase),
            altitude=float(alt if alt is not None else 0.0),
            ambient_temp=float(amb_t if amb_t is not None else 15.0),
            throttle=float(thr if thr is not None else 0.0),
            load=float(lod if lod is not None else 0.0),
            rpm=float(rpm_val if rpm_val is not None else 0.0),
            cht=float(cht_val if cht_val is not None else 0.0),
            egt=float(egt_val if egt_val is not None else 0.0),
            oil_temp=float(oil_t if oil_t is not None else 0.0),
            oil_pressure=float(oil_p if oil_p is not None else 0.0),
            fuel_flow=float(fuel_f if fuel_f is not None else 0.0),
            vibration=float(vib if vib is not None else 0.0),
            source=str(self.source_id),
            source_type=str(self.source_type.value).lower(),
            map_bar=self.get_value("map_bar", self.get_value("map")),
            charge_air_temp=self.get_value("charge_air_temp"),
            engine_rpm=self.get_value("engine_rpm", self.get_value("rpm")),
            propeller_rpm=self.get_value("propeller_rpm"),
            cht_cyl1=self.get_value("cht_cyl1"),
            cht_cyl2=self.get_value("cht_cyl2"),
            cht_cyl3=self.get_value("cht_cyl3"),
            cht_cyl4=self.get_value("cht_cyl4"),
            egt_cyl1=self.get_value("egt_cyl1"),
            egt_cyl2=self.get_value("egt_cyl2"),
            egt_cyl3=self.get_value("egt_cyl3"),
            egt_cyl4=self.get_value("egt_cyl4"),
            coolant_temp=self.get_value("coolant_temp"),
            tcu_wastegate_position=self.get_value("tcu_wastegate_position"),
            metadata=dict(self.metadata),
        )
        return rec

    @classmethod
    def from_telemetry_record(
        cls,
        record: TelemetryRecord,
        source_type: Optional[SourceType] = None,
        source_id: Optional[str] = None,
        ingest_timestamp: Optional[float] = None,
    ) -> "CanonicalTelemetryPacket":
        """
        Lossless and validated ingestion of an existing TelemetryRecord into a CanonicalTelemetryPacket.
        Ensures simulator outputs participate seamlessly in the Phase 9 canonical structure.
        """
        st = source_type
        if st is None:
            raw_st = getattr(record, "source_type", "simulated").upper()
            if "SIM" in raw_st:
                st = SourceType.SIMULATOR
            elif "REPLAY" in raw_st:
                st = SourceType.REPLAY
            elif "REAL" in raw_st:
                st = SourceType.REAL_SENSOR
            else:
                st = SourceType.SIMULATOR

        sid = source_id or getattr(record, "source", "simulator_v1")
        t = float(record.timestamp)
        ing_t = ingest_timestamp if ingest_timestamp is not None else t
        lat = ing_t - t if ingest_timestamp is not None else 0.0

        channel_units = {
            "altitude": ("m", record.altitude),
            "ambient_temp": ("degC", record.ambient_temp),
            "throttle": ("%", record.throttle),
            "load": ("%", record.load),
            "rpm": ("RPM", record.rpm),
            "cht": ("degC", record.cht),
            "egt": ("degC", record.egt),
            "oil_temp": ("degC", record.oil_temp),
            "oil_pressure": ("bar", record.oil_pressure),
            "fuel_flow": ("L/h", record.fuel_flow),
            "vibration": ("g", record.vibration),
        }

        optional_fields = [
            ("map_bar", "bar", record.map_bar),
            ("charge_air_temp", "degC", record.charge_air_temp),
            ("engine_rpm", "RPM", record.engine_rpm),
            ("propeller_rpm", "RPM", record.propeller_rpm),
            ("cht_cyl1", "degC", record.cht_cyl1),
            ("cht_cyl2", "degC", record.cht_cyl2),
            ("cht_cyl3", "degC", record.cht_cyl3),
            ("cht_cyl4", "degC", record.cht_cyl4),
            ("egt_cyl1", "degC", record.egt_cyl1),
            ("egt_cyl2", "degC", record.egt_cyl2),
            ("egt_cyl3", "degC", record.egt_cyl3),
            ("egt_cyl4", "degC", record.egt_cyl4),
            ("coolant_temp", "degC", record.coolant_temp),
            ("tcu_wastegate_position", "fraction", record.tcu_wastegate_position),
        ]

        measurements: Dict[str, CanonicalMeasurement] = {}

        for ch_name, (unit_str, val) in channel_units.items():
            val_f = float(val) if val is not None else None
            quality_status = DataQualityStatus.VALID if val_f is not None and not math.isnan(val_f) else DataQualityStatus.MISSING
            measurements[ch_name] = CanonicalMeasurement(
                channel_name=ch_name,
                value=val_f,
                unit=unit_str,
                raw_value=val,
                raw_unit=unit_str,
                timestamp=t,
                source_timestamp=t,
                ingest_timestamp=ing_t,
                latency=lat,
                source_id=sid,
                source_type=st,
                quality=quality_status,
                status=QuantityStatus.MEASURED if quality_status == DataQualityStatus.VALID else QuantityStatus.UNAVAILABLE,
            )

        for ch_name, unit_str, val in optional_fields:
            if val is not None:
                val_f = float(val)
                quality_status = DataQualityStatus.VALID if not math.isnan(val_f) else DataQualityStatus.MISSING
                measurements[ch_name] = CanonicalMeasurement(
                    channel_name=ch_name,
                    value=val_f,
                    unit=unit_str,
                    raw_value=val,
                    raw_unit=unit_str,
                    timestamp=t,
                    source_timestamp=t,
                    ingest_timestamp=ing_t,
                    latency=lat,
                    source_id=sid,
                    source_type=st,
                    quality=quality_status,
                    status=QuantityStatus.MEASURED if quality_status == DataQualityStatus.VALID else QuantityStatus.UNAVAILABLE,
                )

        return cls(
            timestamp=t,
            source_timestamp=t,
            ingest_timestamp=ing_t,
            latency=lat,
            source_id=sid,
            source_type=st,
            schema_version="1.0",
            engine_id=record.engine_id,
            mission_id=record.mission_id,
            mission_phase=record.mission_phase,
            measurements=measurements,
            metadata=dict(record.metadata),
        )
